### ISSUE TITLE
For HCSR04 must specify pin in registerSensor or it will be ignored.

### ISSUE THREAD

**Issue by Binky7** [mysensors/NodeManager#228]
Hi,

This doesn't work, the sensor gets ignored
``` 
  ChildId=nodeManager.registerSensor( SENSOR_HCSR04);
  SensorHCSR04 *Dist=(SensorHCSR04 *)nodeManager.getSensor(ChildId);  
  Dist->setTriggerPin(6);
  Dist->setEchoPin(5);
```

This is because _pin (in the parent object) isn't being set even though the trigger and echo pins are being set in later calls. This causes the sensor to be ignored in the loop.

The work  around is to set the pin like;

```
   ChildId=nodeManager.registerSensor( SENSOR_HCSR04, 6);
```
but it would be nice if the setTriggerPin method also set  _pin in the parent.

**Comment by user2684** [comment]
Hi, thanks for you comment. This is somehow by design, you must set a pin when registering a sensor not using i2c, otherwise the sensor will be ignored. By default if I remember correctly the echo pin will be set to trigger pin +1 and can be customized later of if needed with setTriggerPin() and setEchoPin(). Agree with you would be better to have setTriggerPin() setting also _pin but I'm afraid would be impossibile with the current implementation since registerSensor() will ignore sensors without a valid pin set :-(
