### ISSUE TITLE
1.7 add commented #define for rf69 frequency 433

### ISSUE THREAD

**Issue by WinndyBoy** [mysensors/NodeManager#309]
In the now commented example. Just wondering why you changed from config.h to inlineing everything into the sketch ?

**Comment by user2684** [comment]
Hi, everything from config.h has been moved into the main sketch to simplify the configuration since having it split between config.h and the main sketch itself was not ideal. Now everything is into a single place, also easier to copy paste and share. Regarding your point, RFM69 directives are all commented out, likewise v1.6 so no difference here. Is my understanding correct? Thanks

**Comment by WinndyBoy** [comment]
I just mean to add a line with a different freq 433, so it can be uncommented, nothing important really, just for completness

**Comment by user2684** [comment]
Sure, this can be done easily

**Comment by WinndyBoy** [comment]
:)

**Comment by user2684** [comment]
Added through #312  `//#define MY_RFM69_FREQUENCY RFM69_433MHZ` to the main sketch and removed any reference to RFM69_868MHZ since RFM69_868MHZ is the default value
