### ISSUE TITLE
Send a heartbeat when waking up from a wait cycle

### ISSUE THREAD

**Issue by Shagrat2** [mysensors/NodeManager#50]
Append Heartbeat for timer

**Comment by user2684** [comment]
Hi, what do you mean exactly? A hearbeat is sent automatically when waking up from sleep. Do you mean to do something similar also after a wait cycle?

**Comment by Shagrat2** [comment]
For the battery - if you do not send data (sensors data no change - is set setTackLastValue)
For no sleep - Does not have battery status and sensors (electronic lock or sprinkler) - send "I'm alive"

**Comment by user2684** [comment]
Ok, so for non sleeping nodes, battery status reports are sent if the node is in a WAIT cycle (wait or sleep is handled in the same way by NodeManager). You are saying, what about a node which is not sleeping AND not using wait. True, they will not send out battery level notifications. BUT I'd recommend in that case to set a sleep (WAIT) cycle anyway. E.g. 1 day wait cycle and battery reports every 1 cycle. Actuators (relay, switch, etc.) do nothing during loop() so it is safe to set a sleeping cycle and when needed you can interact with them by sending a message. Does it make sense? You have a point though since when using wait you can get a battery level but you don't get any heartbeat. I've opened #58 for this

To your other point, what if setTackLastValue() is set and the data does not change. You should get battery level reports in this case even if the value does not change since the battery report routine in the code is called regardless if the sensor is reporting or not any data.

**Comment by Shagrat2** [comment]
My node not have battery. What status to be sent?

**Comment by user2684** [comment]
ok, without battery you then need to wait for #58 so to have a heartbeat sent out periodically. Is this what you needed right?

**Comment by Shagrat2** [comment]
Yes

```
// setup
void setup() { 
  wdt_enable(WDTO_8S);    
  lastSend=millis();    
}

// loop
void loop() {
  currentTime = millis();

  // call NodeManager loop routine
  nodeManager.loop(); 

  // Send feq
  if (currentTime - lastSend > SEND_FREQUENCY){
    sendHeartbeat();     
    lastSend=currentTime;
  }
} 
```

**Comment by user2684** [comment]
Ok perfect, this is exactly what I had in mind even if the implementation will be slightly different (with a WAIT cycle). I'll merge #58 here then since they are referring to the same thing. Keep on eye on this issue and ignore #58 then.
